config/routes.rb
Demo::Application.routes.draw do
  get "say/hello"
  get "say/goodbye"

  root 'say#hello'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @files=Dir.glob('*')
  end

  def goodbye
  end
  
	def say_goodnight(name)
	result = 'Good night, ' + name 
  return result
	end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!!!</h1>
<p>
  E' stato bello averti qui! vieni a trovarci prossimamente!
</p>

<p>
<!-- Say <a href="/say/hello">Hello</a>! -->
Lo vuoi già rifare??? Dimmi <%= link_to "Hello", say_hello_path %> di nuovo!
</p>

app/views/say/hello.html.erb
<html>
<head>
	<title>Hello, Rails!</title>
</head>
<body>
	<h1>Benvenuto da Mika!</h1> 
	<p>Sei qui in questo tempo: <%= @time %> </p>
	<p>
		Ed è una bellissima giornata. Come che ne so? fuori non c'è il sole? piove? ma non in quel senso! <br>
		<br>
		Nel senso che hai cliccato su questa pagina web.<br>
		<br>
		Perché tu "vedi" solo una semplice pagina web con del testo e delle stupidaggine scritte... invece no.<br>
		<br>
		Non lo è.<br>
		<br>
		E' un portale: una porta verso un nuovo mondo. <br>
		<br>
		Di cosa sto parlando? Easy. <br>
		<br>
		Per realizzare questa semplice pagina web ho dovuto imparare delle nuove cose... e sono cose "meravigliose"! Increbili e soprattutto funzionali! <br>
		<br>
		Io ora te le dico, poi se vuoi, le vediamo insieme!<br>
		<br>
		<ul>
			<li>Git
			<li>Github
			<li>PostgreSQL
			<li>Heroku
			<li>Ruby
			<li>Rails
		</ul>
	<br>	
	</p>
	<p>
	  Come? è il tempo di salutarmi? Ooookkkkk! 
	  <%= link_to "Goodbye", say_goodbye_path %>!
	</p>

</body>
</html>